<a href="https://colab.research.google.com/github/olyich/DigitalLiteracy/blob/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_3/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа по теме: "Введение в анализ данных. Операции над векторами и матрицами в NumPy"

In [ ]:
import numpy as np

### Задание 1

Создать 12x12 единичную матрицу (с единицами по диагонали)

In [3]:
import numpy as np

# Создаем единичную матрицу 12x12
identity_matrix = np.eye(12)

print("array",identity_matrix)

array [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Задание 2 *

Создать 9x9 матрицу и заполнить её в шахматном порядке

In [4]:
import numpy as np

chessboard = np.zeros((9, 9), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1

print(chessboard)

[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


### Задание 3

Отсортировать произвольный вектор в порядке возрастания

In [6]:
import numpy as np

np.random.seed(42)

vector = np.random.random(10)

print("Исходный вектор:", vector)

sorted_vector = np.sort(vector)

print("\nОтсортированный вектор:", sorted_vector)

Исходный вектор: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]

Отсортированный вектор: [0.05808361 0.15599452 0.15601864 0.37454012 0.59865848 0.60111501
 0.70807258 0.73199394 0.86617615 0.95071431]


### Задание 4

Определить есть ли в произвольном двумерном массиве из целых чисел строки, в которых все значения равны 4.

In [9]:
import numpy as np

np.random.seed(42)
fourth_array = np.random.randint(3, 5, (8, 3))

result = np.any(np.all(fourth_array == 4, axis=1))

print(result)

False


### Задание 5

Создайте массив из 6 элементов, 5 из которых равны 0, последний элемент должен быть равен 1

In [10]:
import numpy as np

arr = np.zeros(6)
arr[-1] = 1
print(arr)

[0. 0. 0. 0. 0. 1.]


### Задание 6

Укажите индекс 9 элемента в массиве 2х3х2

In [14]:
import numpy as np

arr = np.arange(12).reshape(2, 3, 2)

index = np.unravel_index(8, (2, 3, 2))

index_normalized = tuple(map(int, index))

print(index_normalized)

(1, 1, 0)
